[server]
enableStaticServing = true

[[theme.fontFaces]]
family="alexandria"
url="Alexandria:https://fonts.googleapis.com/css2?family=Alexandria:ital,wght@0,400..700;1,400..700&display=swap"

[theme]
base = 'dark'
font = "alexandria"
backgroundColor = "#101222"
dataframeBorderColor = "#707280"
dataframeHeaderBackgroundColor = "#101222"
textColor = '#ffffff'
